[project]
name = "rstudio-operator"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "jinja2>=3.1.6",
    "kopf>=1.38.0",
    "kubernetes>=34.1.0",
]

[dependency-groups]
dev = [
    "pytest>=9.0.1",
]
